spring:
  application:
      name: zuulService
  datasource:
    thymeleaf:
        mode: HTML5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  #该时间是 zuul 转发请求的超时时间 。超过此时间，zuul 无法向下转发，报500错误
  ReadTimeout: 60000